name: Health Check

on:
    push:
      branches:
        - main

jobs:
  health-check-schedule:
    runs-on: ubuntu-22.04
    steps:
      - name: Check deployed URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-aged-log-1095.fly.dev/health