name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: run e2e tests
        run: npm run test
        
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy app with fly
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}